### ISSUE TITLE
Move Joe's Amazon instance over to an OpenWorm-owned one

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#104]
1. As you can see in the current install instructions, [https://github.com/joebowen/movement_validation_cloud/blob/master/INSTALL.md](https://github.com/joebowen/movement_validation_cloud/blob/master/INSTALL.md), @joebowen 's personal ElasticBeanstalk environment is being used.  Not only does this cost @joebowen money, it would be better to move to OpenWorm.

2. Also, the GitHub repository master should be moved into the OpenWorm organization

**Comment by MichaelCurrie** [comment]
@JimHokanson moved the GitHub repository over at least:
[https://github.com/joebowen/movement_validation_cloud](https://github.com/joebowen/movement_validation_cloud) is now at
[https://github.com/openworm/movement_validation_cloud](https://github.com/openworm/movement_validation_cloud)

**Comment by MichaelCurrie** [comment]
We should also follow [this procedure](http://stackoverflow.com/questions/2763006/) to make the openworm version of the GitHub repo become the master.

**Comment by MichaelCurrie** [comment]
As for moving Joe's ElasticBeanstalk environment, can we move it to something owned by the OpenWorm organization?  Does something like this currently exist?  @tarelli , perhaps you could shed some insight here?

Thanks

**Comment by slarson** [comment]
One question is -- does this need to be up 24/7 now?  Can we put it up and
take it down when it is ready to demo?
ᐧ

**Comment by MichaelCurrie** [comment]
I think yes, since:

For development purposes I think it will be necessary to be able to commit a change to GitHub, and then immediately view it on the website, and so on.

Since AWS charges by the CPU cycle, it shouldn't cost much as long as no one is using it.

As for storage, we wouldn't need much while in development, just enough for our [example data](https://drive.google.com/folderview?id=0B7to9gBdZEyGNWtWUElWVzVxc0E&usp=sharing), which is about 2 GB.

**Comment by MichaelCurrie** [comment]
We have another server now doing what Joe Bowen's machine did.  So we can close this issue now.
