### ISSUE TITLE
Update Examples folder with README

### ISSUE THREAD

**Issue by JimHokanson** [openworm/open-worm-analysis-toolbox#106]
Create a README in the examples folder that gives a quick overview of what each file does

**Comment by MichaelCurrie** [comment]
I feel like each example has an explanation docstring at the top of the file.  It looks like there isn't much will to maintain a separate file which might quickly lose sync with the individual files.  It's not a bad idea but perhaps we should close this issue for now?  I'll do that but feel free to re-open if you disagree.
