### ISSUE TITLE
Get database loaded with example data

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#110]
Currently the only time worm data is compared is when groups of videos are aggregated and compared statistically.  But this data could be compared and quantified in many different ways, to answer questions like:

- How many hours of video were recorded?
- How many frames were segmented?
- What is the average length of the worms collected by one lab vs the worms in another lab?
- How many features are time-series features?  (introspection of the feature definitions themselves!)
- Do some videos have an erratic worm length compared to other videos, possibly indicating segmentation failures?
- Etc.

These questions are easily answered by SQL queries if the data is stored in a relational database.  But currently the data comes in as videos and at all intermediate steps the data remains in file-based silos.
This approach would help to achieve the aim of the title of the “C. elegans behavioural database”

**Comment by MichaelCurrie** [comment]
I've been reading some articles on how we're facing a difficulty here, given how right now features are in objects, and I want them to be in a database.  This requires an objects-to-relational mapping, which is known as the ["Vietnam of Computer Science"](http://blogs.tedneward.com/2006/06/26/The+Vietnam+Of+Computer+Science.aspx) (written from an American perspective, so this refers to their quagmire of the 1960s-70s war in Vietnam).

[Further comments on how to resolve this issue](http://java.dzone.com/articles/martin-fowler-orm-hate)

**Comment by MichaelCurrie** [comment]
Basically the conclusion of my research is that the Object Relational Mapper (ORM) we [should be using](http://stackoverflow.com/questions/5632677/what-is-the-difference-between-sqlite3-and-sqlalchemy) is [SQLAlchemy](http://www.sqlalchemy.org/).

SQLAlchemy supports MySQL, SQLite, and Postgresql, which are the only three conceivable database options we might choose, and replaces commands that might look like this:

```String sql = "SELECT ... FROM persons WHERE id = 10";
DbCommand cmd = new DbCommand(connection, sql);
Result res = cmd.Execute();
String name = res[0]["FIRST_NAME"];```

into commands that look like this:

```Person p = repository.GetPerson(10);
String name = p.FirstName;```

**Comment by MichaelCurrie** [comment]
Another option other than SQLAlchemy is [Django's embedded ORM](http://www.pythoncentral.io/sqlalchemy-vs-orms/), which I believe @joebowen used in his implementation of the database.

**Comment by JimHokanson** [comment]
Django (and others) provide web interfaces which might be nice for some users. With a web interface we'd need server support (which is doable) as well as an API, which I've heard is relatively easy. The web interface should also support operations on remote data.

**Comment by MichaelCurrie** [comment]
The database schema is here:

https://github.com/openworm/movement_validation/tree/master/documentation/database%20schema

A critical thing will be making the schema flexible enough to handle the Brown Lab's new multiworm data.  This includes adding the notion of a "plate feature".

**Comment by MichaelCurrie** [comment]
We are doing a multiworm schema, but a simpler one than was attempted here.  It's captured in existing open issue https://github.com/openworm/open-worm-analysis-toolbox/issues/194
