### ISSUE TITLE
Cloud use case:  View a time-series plot of a feature

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#113]
It should be possible from the web interface to call up a time-series plot of a feature of a worm wireframe that's stored in the database.

That's what was possible from the [WT 2.0 Matlab winforms interface](https://docs.google.com/document/d/1QR_u3VtxOPsC-6teVDFrgEFXxR9lvhUZs-CqSt7FuUk/edit?usp=sharing):

![image](https://cloud.githubusercontent.com/assets/5267078/6223932/6d68a88c-b630-11e4-8373-366861249f02.png)

**Comment by MichaelCurrie** [comment]
This is more advanced, but it would be great to be able to view a worm animation alongside time-series and event features as they occur, or
The raw video overlaid with the CV segmentation (again following the WT 2.0 functionality):
![image](https://cloud.githubusercontent.com/assets/5267078/6223947/9db21a32-b630-11e4-8456-458a18b4c752.png)

**Comment by tarelli** [comment]
@MichaelCurrie when can we talk about interactions with Geppetto?

**Comment by MichaelCurrie** [comment]
@tarelli there are currently three issues of relevance for Geppetto, I think:

1. [The input from Geppetto to movement_validation](https://github.com/openworm/movement_validation/issues/77).  This is my highest priority and we discussed it at the latest meeting - I'm working on a serialized file format for this, perhaps [JSON](http://stackoverflow.com/questions/3488934/simplejson-and-numpy-array)

2. [The output from movement validation to Geppetto (i.e. the fitness function)](https://github.com/openworm/movement_validation/issues/109)

3. This issue, which might be able to somehow use Geppetto's widgets rather than something that would connect our existing matplotlib plotting code to the [AWS webpage](http://movementvalidationcloud-62stvg2sk3.elasticbeanstalk.com/), which might take the form of [mplh5canvas](https://code.google.com/p/mplh5canvas/)

**Comment by tarelli** [comment]
@MichaelCurrie that's great, what I would like to do is to draw a diagram that capture the flows between the systems so that we can start hashing out some of the details.

**Comment by MichaelCurrie** [comment]
This issue is sort of a duplicate of https://github.com/openworm/movement_validation/issues/91.  I'll leave both open for now.

**Comment by MichaelCurrie** [comment]
Here's a cool web-based visualization that could be applied to worm strains, using d3:

http://www.nytimes.com/interactive/2013/09/25/sports/americas-cup-course.html?_r=0

**Comment by MichaelCurrie** [comment]
For now I will close this since we have no plans to implement this right now.
