### ISSUE TITLE
Incorporate André Brown behavioural syntax

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#117]
Here's a link to the [codebase](https://drive.google.com/folderview?id=0B_VNRzddcictbnFjWURqVXBKWUE&usp=sharing_eid), which is GPL'd so we'll have to be careful to keep this code separate from the rest of our code to [avoid violating the terms of the license](https://groups.google.com/forum/#!searchin/openworm-discuss/gpl/openworm-discuss/Ab0MrGRCwoY/5uOhcleopKcJ).

Aidan Rocke is thinking of working on this, in May 2015 after his exams are done in late April.

**Comment by JimHokanson** [comment]
For reference, here's the paper:
http://www.pnas.org/content/110/2/791.short

Aidan mentioned that he might be working on a different paper ...

@AidanRocke Can you clarify which paper you are referring to? "behavioral syntax"

**Comment by AidanRocke** [comment]
Yes. I started working on 'behavioral syntax' and I think I can get it done
in two weeks.

I read the paper and actually understand what is required to make it work.
But, are we
planning to use all three movement validation approaches to test on the
worm simulation
at the end of June?

And is our null hypothesis that the simulated worm will behave like N2
worms?

**Comment by JimHokanson** [comment]
@AidanRocke 

Can you clarify what the three approaches are? My intention was to use as much information as we have available. However as the algorithms develop it will may prove useful to ignore certain features.

At this point, I think we would be happy with a simulation that is like any real worm, not just N2s. I think an ideal comparison point would be to include all recorded real worms and to compare the simulation to the group.

Also, to others for reference. The 'Behavioral Syntax' implementation is currently being worked on at:
https://github.com/AidanRocke/behavioral_syntax_in_Python

**Comment by AidanRocke** [comment]
@JimHokanson 

The three approaches I meant were: SegWorm, Motif Analysis, and behavioral syntax. 

I am currently in Lyon where I don't have access to an offline Python interpreter that can call the Python packages I need. But, I will be back in Edinburgh tomorrow. I can probably make some decent progress if I had access to a decent python interpreter in browser.

Might anybody know a python interpreter 'in browser' that does a better job than Wakari?

**Comment by MichaelCurrie** [comment]
We had a significant discussion about this at the [17 July 2015 movement validation meeting](https://docs.google.com/document/d/1-mzLg7JynAyf3uurBj0OjZdzUaKlksdxunXEUYQtp3E/edit?usp=sharing): basically @AidanRocke has a repository for this here: https://github.com/AidanRocke/behavioral_syntax, but it's "behavioural syntax" not "Motif Analysis", as that's the approach that both he and André favour now.

**Comment by MichaelCurrie** [comment]
Hi @AidanRocke I still need to do a code review here, but do you think we are close to marking this one off as complete?  Thanks!

**Comment by AidanRocke** [comment]
Yes. I'd like to know what you think about the structure of my code.

Cheers,

Aidan

**Comment by MichaelCurrie** [comment]
At this point we have no plans to add additional features so I will mark this as WONTFIX but perhaps that will be revisited by @aexbrown later.
