### ISSUE TITLE
Push out a release that can be installed on pip

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#139]
Push out a release that can be installed on pip

**Comment by MichaelCurrie** [comment]
The modern way to do this is not via egg (which are installed via the earlier tool easy_install) but via a wheel (which are installed via the newer tool pip):

https://packaging.python.org/en/latest/pip_easy_install.html

[Instructions on using wheels](http://pythonwheels.com/)

**Comment by MichaelCurrie** [comment]
As described here:
http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/

1. Create a setup.py file
2. Register a username/password with PyPi https://pypi.python.org/pypi?%3Aaction=register_form
3. Do this:

python setup.py sdist
python setup.py bdist_wheel
python setup.py register
twine upload dist/*

4. Look for your package on the PyPi site:
https://pypi.python.org/pypi?%3Aaction=index

5. On another machine try running:

pip install [your package name]

**Comment by ver228** [comment]
I send a pull request for the setup.py file. I didn't include the version number since I couldn't find it.
I didn't upload it to pip since probably it would be better if Jim or Micheal control the PyPI account.

**Comment by MichaelCurrie** [comment]
@ver228 no problem, I will work on this.

**Comment by MichaelCurrie** [comment]
This is done now:

https://pypi.python.org/pypi/open_worm_analysis_toolbox

I haven't tested it much yet.  Looking forward to hearing your feedback on this, everyone.  This is an exciting moment for the project: after nearly 3 years of work, this is our first official release.  I numbered it 3.0.0 to put us past both the 1.3.4 numbering of the Schafer Lab analysis toolbox and the original WT 2.0 tracker numbering.
