### ISSUE TITLE
Calculated NormalizedWorm does not match loaded NormalizedWorm

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#141]
In [`test_normalized_worm_creation.py`](https://github.com/openworm/movement_validation/blob/master/examples/test_normalized_worm_creation.py), now that `NormalizedWorm.__eq__` has been implemented, I'm getting the following errors when comparing `nw == nw_calculated`:

```
Corr value too low for angles: 0.996
Type mismatch <class 'numpy.ndarray'> vs <class 'list'>: widths
Shape mismatch (4642,) vs (49, 49): length
Corr value too low for area: 0.987
```

As a consequence of this I cannot run the following line:

```
...
wf = WormFeatures(nw_calculated, video_info, fpo)
```

So, some work needs to be done here.

**Comment by MichaelCurrie** [comment]
OK I've fixed the shape problems.  Basically:
- lengths was wrong because of an erroneous assumption that we needed a running total length along the skeleton, when the actual data from the Schafer lab is just one skeleton length per frame.  Fixed by 541724b11d519bf94e907a37058ed62a29aac5bf.
- widths wasn't getting normalized.  Fixed by dbca43ecb4f02c3cec7e6c7d878ddffad72b17c7.

Now the errors when comparing `nw == nw_calculated` are:
```
Corr value too low for angles: 0.996
Corr value too low for widths: 0.996
Corr value too low for length: 0.954
Corr value too low for area: 0.987
Time elapsed: 168.42s
```

Not bad.  Next steps would be probably to look at the old code to do some white-box testing and compare the code to find the source of these little differences.

**Comment by MichaelCurrie** [comment]
It's possible the chain-code calculation is somehow off.  Here are some links discussing chain codes that I'll use with my further work on this:

http://stackoverflow.com/questions/22326412/how-to-get-freeman-chain-code-in-opencv
https://books.google.ca/books?id=ue0C-a59db0C&pg=PA29&lpg=PA29&dq=herbert+freeman+1961&source=bl&ots=qhR6IPaEcf&sig=o3RqVnPOGChksXGjSfTDUhJ7cnA&hl=en&sa=X&ei=216GVYmTN5KCgwTw6oEw&ved=0CD0Q6AEwBg#v=onepage&q=herbert%20freeman%201961&f=false
http://www.researchgate.net/publication/200578550_A_Chain_Code_Approach_for_Recognizing_Basic_Shapes
http://www.ijaiem.org/volume2issue8/IJAIEM-2013-08-31-081.pdf

https://github.com/openworm/SegWorm/blob/a04917112facc8e880e24da1cbf134243bd9c0be/docs/SegWorm/SegWorm/Worms/Printing/methodsTIF.html

https://github.com/openworm/SegWorm/blob/a04917112facc8e880e24da1cbf134243bd9c0be/Worms/Segmentation/cleanSkeleton.m

**Comment by JimHokanson** [comment]
Given that we are using different algorithms for calculating the skeleton (and thus the width & length) and that a different algorithm for the area, I think we are all set.

**Comment by MichaelCurrie** [comment]
I think I forgot to close this after Jim explained the reason for these differences.  Closing now.
