### ISSUE TITLE
WormPlotter Animated Plot Issues in OS X

### ISSUE THREAD

**Issue by clinzy** [openworm/open-worm-analysis-toolbox#151]
As is the WormPlotter code sets blit=True (worm_plotter.py line 259)  which causes the following error with matplotlib on OS X:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/animation.py", line 855, in _blit_clear
    a.figure.canvas.restore_region(bg_cache[a])
AttributeError: 'FigureCanvasMac' object has no attribute 'restore_region'

Setting blit=False per http://stackoverflow.com/questions/13216520/mac-osx-attributeerror-figurecanvasmac-object-has-no-attribute-restore-reg resolves this error and allows the animation to continue.

A second error is revealed 'Python[5706] <Error>: CGContextClosePath: no current point.' that causes the plot animation to studder. Per https://github.com/matplotlib/matplotlib/issues/3654 this seems to be a Python on OS X issue.

**Comment by tacaswell** [comment]
The first issue should be fixed in mpl 2.0 as the OSX backend is now Agg based.  You can test with with the beta release

**Comment by MichaelCurrie** [comment]
I will mark this as wontfix since we will use WCON viewer and d3.js in movement_cloud to visualize worms now.

**Comment by tacaswell** [comment]
:disappointed:
