### ISSUE TITLE
Investigate these client-server examples

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#158]
Here are some examples of platforms featuring a server side with lots of data, and a thin client side making analysis requests to the server.

- Geppetto

**Comment by JimHokanson** [comment]
Apparently in Canadian some can be singular ... :stuck_out_tongue:

**Comment by MichaelCurrie** [comment]
A couple more were mentioned in the meeting but I forgot their names!  @slarson and @pgleeson had a couple of examples as I recall.  Gentlemen, can you help save me from Jim's hackle-raising?

**Comment by pgleeson** [comment]
Widely used in the bioinformatics community:
https://galaxyproject.org/

You could have a look at this too, new feature "Tables" for structured web friendly queries
https://www.synapse.org

**Comment by MichaelCurrie** [comment]
This issue is now moot as we're using Django for administering the database, and not using those platforms.  (for the moment).  Both Galaxy and Synapse appear to be something that we could look into in the future though.  Thanks!
