### ISSUE TITLE
Switch to new features organization

### ISSUE THREAD

**Issue by JimHokanson** [openworm/open-worm-analysis-toolbox#164]
We still need to remove the old feature organization approach and transition to the new one. This requires changing the stats code.

@MichaelCurrie Let's get this done soon. Let me know if you want help with anything.

**Comment by MichaelCurrie** [comment]
I agree, and as a first step I was validating that the features still calculate.  Hence my debugging `validate_features.py`.  I guess you're saying that the test of the new features code is actually in `test_new_feature_organization.py`, though, so once I make sure `validate_features.py` works I'll try out `test_new_feature_organization.py`.

Once that all works I'll work on the statistics code.

**Comment by MichaelCurrie** [comment]
OK I've moved `examples/test_new_feature_organization.py` to `tests/test_features_dos.py`.  It runs great!  (20 seconds and no errors)

**Comment by MichaelCurrie** [comment]
The file for me to change over to `WormFeaturesDos` is `video_to_features.py`, specifically the line:

```
wf = mv.WormFeatures(nw)
```

I'm assuming it's not as simple as changing it to 
```
wf = mv.WormFeaturesDos(nw)
```

Since `HistogramManager` won't be able to access the features in the `wf` object in the same way as before...

I'll start working on it.

**Comment by MichaelCurrie** [comment]
So it looks like the change is to access features, we have the old way:

```
wf_uno.posture.bends.head.std_dev
```

and the new day:

```
wf_dos.get_feature('posture.bends.head.std_dev').value
```

**Comment by JimHokanson** [comment]
That is correct, although I believe that some features may be None (current behavior). This is something that really needs to get written up into a design document (in terms of data guarantees). I had started working on that but I haven't finished it yet. Given that the feature itself is a class which holds a numerical value (in the value attribute), ideally no features would be None, only their values.

The other important point is that you should also be able to iterate over features. Features are stored as a dictionary in the 'features' attribute of wf_dos. The important distinction here is that not all features may be calculated and that one should iterate over the calculated features and not over a list of all features that exist.

**Comment by MichaelCurrie** [comment]
So currently `Specs.specs_factory()` is called by the SimpleSpecs, MovementSpecs and EventSpecs initializers and the CSV list of features passed is in `statistics\feature_metadata`, spread across three CSV files: `event_features.csv`, etc.

In contrast, `WormFeaturesDos` gets its features names from `features\feature_metadata\features_list.csv`.  I will need to change the `Specs` code to also use this CSV file.

Eventually I'd like that file to contain all of the wonderful data from `documentation\database schema\Features Specifications.xlsx`, but that can wait, I think.

**Comment by JimHokanson** [comment]
@MichaelCurrie 
Some thoughts.
Based on our previous discussions, the hope was to not include ALL of the feature specifications in the new csv file.

I think including units and names is fine. I had initially shied away from the idea of including anything related to how to calculate histograms in these files. Perhaps we could include a generic 'type' that any feature could contain and we could decide to process the data differently depending on this type.

type examples - mrc_event, mrc_movement, mrc_simple

At this point let's get something working, I'll leave the design decisions up to you at this point. The above concerns are mainly with regards to new features and not forcing them to fit a specific mold, but perhaps it is best to tackle that problem when we get there.

**Comment by JimHokanson** [comment]
@MichaelCurrie 

I don't like that the feature expansion is done when calculating statistics. It seems like these things should be separated. Any thoughts on how to implement this?

Maybe something like:
```python
expanded_features = features.expand() #maybe allow passing in options
histograms = expanded_features.to_histograms() #Could allow passing in options 

#Then when loading
features = WormFeaturesDos.from_disk([file_paths]) #returns a list of features
#Then the above commands

#Alternatively this would be allowed:
histograms = original_features.to_histograms()
```

Thoughts?

**Comment by MichaelCurrie** [comment]
Yes I like it.  Basically the "specs" code would need to be moved over to the features subpackage.  I'll think about this some more soon.

**Comment by JimHokanson** [comment]
Just an update on where I'm at.

I'm currently trying to implement generate_stats_dos.

The new change is to first load each feature from disk rather than passing them into the histogram manager. From there I'm manually "expanding" the features so that this is an explicit step. I'm almost done with this step, I just need to work out a problem with copying a "simple" feature, which for some reason isn't working. Then I need to create a new feature container that holds the expanded features (and their new specs).

Once this is done I'd like to implement a method that is something like features.compute_histograms which would return a histogram set for that feature set. Another method would merge these sets.

**Comment by JimHokanson** [comment]
Update.

We are currently rewriting features to take care of some edge cases. I just finished implementing the setup for "requested features" as opposed to ones that are just caculated because of dependencies.

**Next Step 1:**
The next step would be to implement get_spec_table() which would return the specs in Pandas.

Then we need to implement a function that computes features based on a list of specs that are passed in.

The first approach that comes to mind is first getting the specs then passing them into the constructor of WormFeaturesDos

After this has been implemented, we need to verify that we can pass in only a subset of specs and that only those specs are returned even though multiple features may have been computed.

Next Step 2:
Implement an empty_feature rather than None. Implement expansion of empty event features. I recommend we have an object that represents the emptiness and that handles equality comparisons (i.e. two objects that both have no events would be equal but if one of those is not computed due to a missing dependency, then they would not be equal)

Next Step 3:
After this has been implemented ideally we can plug it into the old histograms code and we will be done.

**Comment by JimHokanson** [comment]
"Next Step 1" is now done with the latest commit.

See test_spec_filtering()

**Comment by JimHokanson** [comment]
I added a TODO for utils.print_object()

This is sort of a bonus request, but I think it would help me with debugging and in general with user interaction ...

I think we need to first eliminate some values, e.g. the contour of the normalized worm, and then deal with the consequences (e.g. making contour dependent features empty features)

**Comment by JimHokanson** [comment]
Pulled from master. Starting to rewrite tests. 

Next steps:
Populate "empty" attributes (see notes in generic_features.py) in spec loader then add "use_data" or "is_empty" property in the "Feature" class that combines the various attributes. At this point rewrting the feature expansion to use "is_empty" should be trivial, then hopefully the merge_histograms works again!

**Comment by JimHokanson** [comment]
New code has been merged back into master.

Some thoughts on going forward:
1) The new code needs documentation.
2) Might populate WormFeatures with NormalizedWorm values as non-user-requested features and then make requests for these features like we do other dependencies.
3) Need to build in support for missing dependencies. This code has been started but needs some work. It would be good to knock out the contour and then make sure things can fail gracefully.
4) Event signing and filtering could be done in a separate feature manipulation. It was sort of a hack to do this in the feature expansion code.
5) I'm not sure the statistics are being calculated correctly, this needs to be looked at.
6) Histograms need to always be created instead of sometimes returning None
7) There are lots of TODOs in the code that should be made into issues
