### ISSUE TITLE
using reportlab to generate reports

### ISSUE THREAD

**Issue by AidanRocke** [openworm/open-worm-analysis-toolbox#167]
At the Nov. 20 meeting the possibility of automatically generating lab reports in pdf format was discussed as this might interest scientists who currently take maybe 1-2 hours creating reports from matlab-generated calculations and figures. 

Besides this use case, reports might be very useful in step 7 of Stephen's plan for the simulation: https://github.com/openworm/OpenWorm/blob/development/master_openworm.py

Here's a basic tutorial: http://www.blog.pythonlibrary.org/2010/03/08/a-simple-step-by-step-reportlab-tutorial/

**Comment by MichaelCurrie** [comment]
Given our work with movement_cloud to visualize things I think it's safe to say this is not the direction we will be proceeding in at this point.  I will close but it's interesting to note this in case we need to generate reports for a later paper.
