### ISSUE TITLE
Have BasicWorm inherit from WCONWorms

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#169]
This will connect `open_worm_analysis_toolbox` with [the `wcon` package](https://pypi.python.org/pypi/wcon/).

This will allow us to convert Schafer Lab files into WCON files, including by moving the metadata into the file.

After meeting with Jim on 19 Dec, we agreed it would be best to just subclass BasicWorm now, rather than trying to do the same for NormalizedWorm or WormFeatures.

Once this is done we can hand this format off to the team at Sibernetic.

We can accomodate contour information using a type 2 WCON custom feature (inside the "data" object).

**Comment by MichaelCurrie** [comment]
@aexbrown one reason for this will be wanting to take the original Schafer skeleton files and:

- serialize them into WCON format, as well as 
- marrying them with their metadata in that WCON file.

This way each individual worm experiment will have all its data and metadata stored in one place for easy downstream handling.

Questions:
1. Do you agree with this approach?
2. Where is the metadata for the individual skeleton files currently stored?  It must be close by, or even as I recall some of the information was in the directory names of their deeply nested locations.

Thanks

**Comment by aexbrown** [comment]
I do agree with the approach.  After skeletonisation and feature extraction, the analysis pipeline created a file with suffice ‘_features.mat' which contains two structs.  One is called ‘worm' and one is called ‘info'.  The worm struct has the skeletons and other feature data, the info struct has the metadata.  The original metadata that was used to create the info struct is in several places.  Some of it (strain, genotype, time stamp) is in the file name and some of it (frame rate, resolution) is in an info.xml file created by the tracker and stored in the same directory as the original video.

On 27 Dec 2015, at 23:45, Michael Currie <notifications@github.com<mailto:notifications@github.com>> wrote:


@aexbrown<https://github.com/aexbrown> one reason for this will be wanting to take the original Schafer skeleton files and:

  *   serialize them into WCON format, as well as
  *   marrying them with their metadata in that WCON file.

This way each individual worm experiment will have all its data and metadata stored in one place for easy downstream handling.

Questions:
1. Do you agree with this approach?
2. Where is the metadata for the individual skeleton files currently stored? It must be close by, or even as I recall some of the information was in the directory names of their deeply nested locations.

Thanks

**Comment by MichaelCurrie** [comment]
Rather than using inheritance, [I wrote a function that loads a Schafer .MAT file and creates a WCONWorms object](https://github.com/openworm/open-worm-analysis-toolbox/blob/master/examples/WCON%20demo.py).  This currently only works for BasicWorm, and only loads the skeleton, not the contour information.

A next step would be to create a similar function, but to allow a WormFeatures object to be loaded from and save to a custom WCON file that includes feature data.
