### ISSUE TITLE
Missing test file?

### ISSUE THREAD

**Issue by cheelee** [openworm/open-worm-analysis-toolbox#179]
In examples/WCON Demo.py, the referenced test file "testfile4.wcon" appears to not have been checked into the repository.

**Comment by MichaelCurrie** [comment]
Thanks @cheelee - `WCON Demo.py` is a work in progress.  I will work on that.

**Comment by cheelee** [comment]
That's ok, it would work just by plopping in any WCON file and renaming it accordingly!

**Comment by MichaelCurrie** [comment]
I believe this issue no longer exists.
