### ISSUE TITLE
What about a setup.py?

### ISSUE THREAD

**Issue by ver228** [openworm/open-worm-analysis-toolbox#180]
Hello guys, I propose to add a simple setup.py file like:
```
#!/usr/bin/env python

from setuptools import setup

setup(name='open_worm_analysis_toolbox',
      version='0',
      description='open_worm_analysis_toolbox',
      url='https://github.com/openworm/open-worm-analysis-toolbox',
      packages=['open_worm_analysis_toolbox'],
     )
```

As far as I understand if one execute `python setup.py develop `  the links will be local. In this way the module will be easier to import without having to worry about relative paths.

**Comment by MichaelCurrie** [comment]
I believe you are referring to one of the steps involved in getting the package registered with PyPI.  This is already an outstanding issue, #139.  If I am mistaken please feel free to reopen this issue.

I fully agree with you that finishing #139 would be nice.  In a sense it's trivial, but I've been waiting for the package to be "complete" in some sense for doing this.  Perhaps we should at least push out an alpha release now.
