### ISSUE TITLE
OpenCV Travis build failing since ~8 April 2016

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#187]
Sometime in the past month something changed externally that now causes the Travis-CI builds of OpenCV to fail at the `cmake` step.

As you can see in the build history, the builds stopped working after  6c10cef, but that commit didn't change anything of substance that should matter:

https://travis-ci.org/openworm/open-worm-analysis-toolbox/builds

![dfdsfads](https://cloud.githubusercontent.com/assets/5267078/14601894/edf48468-058e-11e6-825c-619a811f6f3c.png)

So someone should investigate and fix the build issue.  @JimHokanson is this something you might be willing to brave once more?

**Comment by JimHokanson** [comment]
Looking at the job the error is from:

CMake Error at CMakeLists.txt:608 (find_package):
  find_package called with invalid argument "CONFIG"

This was updated 28 days ago:
https://github.com/Itseez/opencv/commit/727743809e755b9629301b5145de7909c72f68c0

Old cmake doesn't have a CONFIG option. Presumably we could update cmake ...

http://stackoverflow.com/questions/33196136/travis-ci-update-cmake-using-the-packages-cache

**Comment by cheelee** [comment]
I'll independently give the CMAKE issue a shot, been a while since I've dug there but I probably need the exercise.

**Comment by MichaelCurrie** [comment]
Whoever fixes this should probably fix https://github.com/openworm/open-worm-analysis-toolbox/issues/175 at the same time.

**Comment by JimHokanson** [comment]
I found a few bugs in the Travis CI code. It still seems like the whole process could be simplified even more ...

For OpenCV I transitioned to using a version from conda, rather than building, which shaves 20 minutes off the test time.

For reference I think the error might have been with a hardcoded python version path ...
