### ISSUE TITLE
Populate AWS database with information currently in flat files

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#191]
Currently the [MRC worm behaviour database](http://wormbehavior.mrc-lmb.cam.ac.uk/) has a feature vectors stored in a flat files, one per file.  These feature vectors should be populated into the tables in the AWS database created by #190.

With this information in a relational database, we can run queries like filtering for certain strains or features, or selecting columns like metadata columns or data columns like average speed.

**Comment by ver228** [comment]
Hey Michael, I forgot to mention yesterday that it might be a good idea to use sqlalchemy for this task. I have been using it lately and I am quite happy with it. If we will use python to access to the data it will be cleaner to have everything in the same language.

**Comment by MichaelCurrie** [comment]
OK sounds good.  @ver228 is it okay if I also use pandas for representing the intermediate data structures in memory?

@aexbrown I was hoping to have this done by 30 June but unfortunately I will need another week.  I have revised the milestone target.

**Comment by MichaelCurrie** [comment]
After further discussion with André the next step to accomplish this issue is for me to modify https://github.com/openworm/open-worm-analysis-toolbox/blob/master/examples/WCON%20demo.py so that it saves both the skeleton and both sides of the contour, not just one.

Then @ver228 can iterate over the files on his local machine and generate WCON files.  @ver228 you'll have to map the folder structure to the metadata, since the folder structure has information about the metadata.  I'll let you know when this is done.

**Comment by MichaelCurrie** [comment]
Here is an example file name to be iterated over:

[`unc-63 (ok1075) on food L_2010_04_09__11_44_51___4___5_features.mat`](https://drive.google.com/open?id=0B9dU7zPD0s_LemZ5dlR5d3kyaGkyR2hQZnRTTk96ZHc2RUNN)

Here's the information I can parse from this:

- `unc-63` (strain)
- `ok1075` (?)
- `on food` (on food / not on food)
- `L` (clockwise orientation?)
- '2010_04_09__11_44_51` (recorded 2010-04-09 at 11:44:51 UTC?)
- `4___5` (?)

Plus I believe there is information in the directory structure as well.

**Comment by ver228** [comment]
Hey @MichaelCurrie, the database should have all the information I extracted the information in the file name and in the folder. I would be using the database to populate the fields in the WCON files.

**Comment by MichaelCurrie** [comment]
It looks like @ver228 already did this, iterated over the files, and the database @cheelee is using contains the metadata from the files.  Fantastic.  I will close this issue.
