### ISSUE TITLE
Expand worm database to include multiworm capability

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#194]
The database schema created by #190 could eventually be expanded to handle multiple worms.  I developed a schema for this already, but much of it might be superseded by the re-factoring of OWAT internals in 2015, and also by the metadata conventions in WCON.

**Comment by MichaelCurrie** [comment]
After further discussion with @aexbrown we just need to extend the MRC DB metadata schema to handle multiple worms.  My original work on this in January 2015 intended to handle skeleton and feature data, which is too complicated for the initial database schema.

**Comment by MichaelCurrie** [comment]
@ver228 on 7 July 2016 you mentioned:

> I uploaded a small sample video and of the output files of the multiworm tracker into:

> https://drive.google.com/folderview?id=0B8Kl8D4WTGWGfjVJSmRBSmo3ZzMtaU1WQW00dElCVV9udDNaSEtTa05HRGZ3clFwQ25kQXc&usp=sharing

> I generate the output using the script https://github.com/ver228/Multiworm_Tracking/blob/master/examples/process_single_file.py

However, 

1) I need permission to access the link - perhaps you could add a new link?
2) I cannot find `process_single_file.py` in your repo

Actually I don't think this is necessary for me to do a schema for the multiworm tracker since I only care about metadata.  But if you think it is, I would appreciate if you could do 1 and 2 above.  Thanks

**Comment by ver228** [comment]
Sorry for the late answer.

Yes, I did changed the path for the examples. Google drive was giving me
problems. It did cancel the account a couple of times.

Now I am using the following link:

EXAMPLES_LINK="
https://imperiallondon-my.sharepoint.com/personal/ajaver_ic_ac_uk/_layouts/15/guestaccess.aspx?guestaccesstoken=ldZ18fLY%2bzlu7XuO9mbKVdyiKoH4naiesqiLXWU4vGQ%3d&docid=0cec4e52f4ccf4d5b8bb3a737020fc12f&rev=1
"

I will keep updating this link in the top of the installation_script.sh (
https://github.com/ver228/Multiworm_Tracking/blob/master/installation_script.sh
).
The files the files in the list are the ones used by the test files (
https://github.com/ver228/Multiworm_Tracking/blob/master/Tests/run_tests.py
).

I hope it is useful. Do you know how can I send this info to openworm?
Should I post it in the main conversation?

Best
AEJ

**Comment by MichaelCurrie** [comment]
Closing this issue here, now that it's over at movement_cloud
