### ISSUE TITLE
Store WCON files in a MongoDB database?

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#198]
From @ver228 (I'm making this into a separate issue for clarity):

> if we output our data as a collection of JSON documents, wouldn't it make sense to store them in a MongoDB? That database seems to work be specifically designed for that task. What do you think @MichaelCurrie?

**Comment by MichaelCurrie** [comment]
From what I understand MongoDB is a leading NoSQL database, written in C++, and has Python bindings.

Advantages:
- [From what I am reading](https://stackoverflow.com/questions/9373889/is-mongodb-a-good-choice-for-storing-json-structures) it is great for storing data from JSON files that are changing often and deeply nested, since you don't need to worry about creating a database schema and maintaining it.

Disadvantages:
- Since it's NoSQL, we don't have the advantage of using SQL queries to obtain information from the database.
- [I have been working on using Django's admin feature as a front-end interface to browse the worm database data](https://github.com/openworm/open-worm-analysis-toolbox/issues/193); I am nearly ready.  [It's a bit tricky to make Django work with a NoSQL DB like MongoDB](http://staltz.com/djangoconfi-mongoengine/#/).

So I'd like to proceed as planned with a traditional RDBMS store in MySQL, at least for the next couple of weeks.  If you see what I've made and still feel it would be best to go NoSQL/MongoDB, I'm happy to have that conversation.  :)

**Comment by ver228** [comment]
Well, I think we could use both. We could save a mongoDB ID in the SQL data. The other option is to store the features as WCON text files and store the paths in the database. The advantage of the former is that MongoDB allows queries, data is store in as [BSON](http://bsonspec.org/) that is smaller in size , and allows in-build compression. The distanvantage is that all the data is stored in a single file DB, and there is more risk to loose data.
In anyway, to use MongoDB we need to convert first the data into JSON format. So  can I do that and then we can discuss the merits of MongoDB if necessary.

**Comment by MichaelCurrie** [comment]
Using both sounds good to me, because one way or the other we will have to have a document store, whether it is MongoDB or the file system, so it might as well be MongoDB.

**Comment by MichaelCurrie** [comment]
At the meeting today @Ichoran pointed out that a file store may have the advantage of less complexity and if we are not planning to do any analysis on the JSON files within MongoDB, placing them in such a repository might be more complex with no obvious gain to offset, in our use case.

In any case we can decide after the JSON conversions.  I just wanted to note this somewhere.
