### ISSUE TITLE
Interactive query web interface for MRC DB

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#200]
Currently the MRC DB can be viewed from movement.openworm.org, but you can just browse the tables.
1. We'd like to be able to search through strains, get back a link and Zenodo DOI.
2. We'd like to be able to slice the data using interactive sliders.  D3 and Square's Crossfliter project seem to offer that capability:

https://square.github.io/crossfilter/

http://thematicmapping.org/playground/d3/d3.slider/

e.g. give me strains that are faster than X

**Comment by MichaelCurrie** [comment]
@cheelee is this the sort of selector widget you were looking for?

https://jqueryui.com/selectable/

**Comment by cheelee** [comment]
@MichaelCurrie Not exactly, but that can be a good starting point.

**Comment by MichaelCurrie** [comment]
Our work at https://github.com/openworm/movement_cloud has progressed to the point where we can declare this task complete, or at least enough to close this stub issue.
