### ISSUE TITLE
Upload small sample to sandbox.zenodo.org

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#204]
The manifest will be:
- original video .HDF5  -> a bunch of images compressed with GZIP
- video file     .AVI
- _skeleton      .HDF5
- features file  .HDF5
- WCON           .JSON
- subsampled video file  .AVI  (optional)

@ver228 and @aexbrown can you please give me a link to a few examples of experiments with this manifest, and I will try uploading?  Thanks.

**Comment by ver228** [comment]
Here is the [link](https://imperiallondon-my.sharepoint.com/personal/ajaver_ic_ac_uk/_layouts/15/guestaccess.aspx?folderid=01a1f6c45da4543c99a3efa48afcb303d&authkey=AeVd-3eiHkS30NGfqzYAxOQ) in case you miss it.

**Comment by MichaelCurrie** [comment]
Back in April I did this for a single DOI entry.  https://sandbox.zenodo.org/record/71862#.WUDTjGg1-Cg

![image](https://user-images.githubusercontent.com/5267078/27117919-b57b4c02-508d-11e7-8637-7d8148c74c95.png)

I will close this issue and work on the bulk process over at movement_cloud: https://github.com/openworm/movement_cloud/issues/92
