### ISSUE TITLE
Test features against SegwormMatLabClasses code

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#30]

**Comment by JimHokanson** [comment]
Everything now matches except for posture.bends.head.std_dev which only has a 0.881 correlation. I've been letting values above 0.95 slide. My guess is that the partition definitions are different. Once that problem is identified this issue is done.

**Comment by MichaelCurrie** [comment]
I know you said there's one more issue to identify here but there has been further significant work by Avelino to validate the features calculation against the original Yemini code, and so I think any further effort to compare to your intermediate SegWormMatlabClasses repo is moot.  So I'll close this.
