### ISSUE TITLE
Make the config local

### ISSUE THREAD

**Issue by JimHokanson** [openworm/open-worm-analysis-toolbox#65]
The configuration options are currently global in nature. It would be better if these were passed in locally so that changes to these parameters could be made at run time rather than manually editing the config file.

Also, the options should be cleaned during this process. Each parameter in the config should be identified by its section as well as accompanied by a definition of what it impacts as well as the units of the parameter.

**Comment by MichaelCurrie** [comment]
At this point the only thing left in `config.py` to be moved to `feature_processing_options.py` are the following four variables.  Hopefully one of us can move this soon - I'll try to soon.

```
""" Locomotion Features """
# used in get_velocity:
TIP_DIFF = 0.25
BODY_DIFF = 0.5

# The following two are used in EventOutputStructure...
# When retrieving the final structure
# this is the name given to the field that contains the
# sum of the input data during the event
DATA_SUM_NAME = 'distance'
# same as above but for BETWEEN events
INTER_DATA_SUM_NAME = 'interDistance'
```

**Comment by MichaelCurrie** [comment]
I removed all of the four above as they are not used by any other code anymore.  

So handled by 66f393dc12936257c363ef6bdd220dac4a11fca4.
