### ISSUE TITLE
Get video, contour and pre-features pipeline into the repo

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#77]
We'd like to have the video processing code also be in the pipeline, even if only in outline only for now.  That way it's clear how the pipeline will work.

I'm thinking that the raw video will be encapsulated in an object called **WormVideo**, the contour will be in something called **WormContour**, and pre-features in something called **WormContourPlus** or something.

Then the **WormContourPlus** instance is normalized to become **NormalizedWorm**.

Right now, a very old (circa October 2013) module I created called **SchaferExperimentFile.py** tries to do some of this, but doesn't look at all like the clean pipeline described above.

The idea here is that our simulated worm will directly produce an instance of WormContour.  In contrast, the current Schafer Lab pipeline for the real worm goes from WormVideo to NormalizedWorm, without exposing the intermediate steps.

By exposing all intermediate steps, our pipeline should hopefully be clearer than the Schafer Lab code's approach.

**Comment by MichaelCurrie** [comment]
Here's my assessment of the status of the pre-features code.  Jim's finished several of the calculations but to be fully general some steps still have to be completed, and also in and out touches and areas still need to be implemented:

![image](https://cloud.githubusercontent.com/assets/5267078/7692453/d101f9c8-fd81-11e4-83ee-77638dcc6221.png)

**Comment by JimHokanson** [comment]
Spot on. Areas should be easier. I plan on writing these up as there own
issues in the next day or two.

**Comment by MichaelCurrie** [comment]
I wrote up a [nicer diagram](https://www.lucidchart.com/invitations/accept/56998da5-ae6d-45ca-a09e-0488ce3e1b6b) now.  Same idea, just hopefully more clearly expressed.

![image](https://cloud.githubusercontent.com/assets/5267078/8147283/1cf34e42-1220-11e5-80e5-ab309ffc84dd.png)

**Comment by MichaelCurrie** [comment]
This was done in Summer 2015, not sure why we didn't close it back then.
