### ISSUE TITLE
Update Install Instructions

### ISSUE THREAD

**Issue by JimHokanson** [openworm/open-worm-analysis-toolbox#96]
The install file is still a bit complicated. Things to fix:

1. missing scipy dependency
2. links to all numpy-scipy packages should be provided for windows
3. A google account isn't needed and should be clarified as such
4. Explicit specification of the file paths in user_config should be explained more clearly

**Comment by MichaelCurrie** [comment]
Also I think it should be clarified that the tools at the beginning do not need to be installed first before starting the 1. 2. 3. of the install steps.

**Comment by MichaelCurrie** [comment]
I put the discussion of tools at the bottom, and added the scipy dependency.  I added language explaining how you don't need a Google Drive account, and I believe the user_config explanation is adequate now.

(Three commits ending in b61070c8898bb8f4a36318c2d4eb1a46fb2ad904)
